#!/bin/sh

die () {
    echo "$1"  
    exit 1    
}

write_sbt_script () {
    VERSION=$1
    read -d '' SCRIPT <<EOF
#!/bin/sh
java -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M -jar \`dirname \$0\`/sbt-launch-${VERSION}.jar "\$@"
EOF
    echo "$SCRIPT" > sbt
}

INSTALL_DIR=$HOME/bin

while [[ $# -gt 0 ]]; do
    case "$1" in
        -d)
            INSTALL_DIR=$2
            shift
            shift
            ;;
        *)
            echo "$@"
            VERSION=$1
            shift
            ;;
    esac
done

test -n "$VERSION" || die "VERSION is required."

mkdir $INSTALL_DIR > /dev/null 2>&1

cd $INSTALL_DIR

if [ -f $INSTALL_DIR/sbt ]; then
    read -p "$BIN/sbt already exists. Overwrite? [y/n]" -n 1 -r
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        exit 0
    fi
fi

TYPESAFE_REPO=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch
JAR_URL=$TYPESAFE_REPO/${VERSION}/sbt-launch.jar

wget -O sbt-launch-${VERSION}.jar $JAR_URL

write_sbt_script $VERSION
chmod +x sbt

echo "Successfully installed at $INSTALL_DIR/sbt"